### ISSUE TITLE
Project Structure

### ISSUE THREAD

**Issue by mayur-ravindram** [muhammadkarbalaee/jalgorithm#44]
The project structure is as following (PFA screenshot) when cloned the project.
  ![image](https://user-images.githubusercontent.com/70086176/147880167-5ab7ae25-9cc6-4b92-bf98-bd80427104f3.png)
Can we have a project structure pertaining proper java source code? I faced following issues.
- Project build failed for issues in build.gradle 
 ![image](https://user-images.githubusercontent.com/70086176/147880332-88b14dd6-2149-4b0d-9f3a-4af987d88827.png)
- There were no source folders
- I was not able to add new class/package as source 

Pushing changes to update build.gradle file

**Comment by mayur-ravindram** [comment]
Blocked due to push access to repo.
@muhammadkarbalaee , pls look into it as discussed. 
Will push the code once access issue is resolved.

**Comment by muhammadkarbalaee** [comment]
I opened the push access for collaborators. you can push now.

**Comment by muhammadkarbalaee** [comment]
by the way.... there was a src folder already. you see that.
