### ISSUE TITLE
Bubble Sort implementation is not most efficient

### ISSUE THREAD

**Issue by Hreshi** [muhammadkarbalaee/jalgorithm#66]
The current implementation of bubble sort goes from first index to last index in every loop. As each loop in Bubble Sort shifts the largest element to right there is no need to check for already sorted array on right side. [https://github.com/muhammadkarbalaee/jalgorithm/blob/e6bd6b2121c46f427f464097c3760b7456f04b80/src/main/java/io/github/jalgorithm/algorithms/sorts/BubbleSort.java#L45](url)

**Comment by muhammadkarbalaee** [comment]
That's true.
