### ISSUE TITLE
Add a `reverse()` method to Linked List implementation 

### ISSUE THREAD

**Issue by ybrenning** [muhammadkarbalaee/jalgorithm#85]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
I would like to add a simple `reverse()` method to the `TailedDoublyLinkedList` class which would reverse the order of the current Linked List. Doubly Linked Lists are especially convenient for this algorithm as they allow you to swap previous and next reference pointers. I would like to add this method to the class as it is a fairly common algorithm and should be included in this implementation.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by muhammadkarbalaee** [comment]
That's a nice feature indeed. Go on. Your contribution is very welcome.

**Comment by muhammadkarbalaee** [comment]
please make a new branch and add the feature and when you are done, make a pull request to development branch. We'll review and merge your implementation. 
ich danke ihn😊

**Comment by muhammadkarbalaee** [comment]
If you had trouble with reading any part of the code, feel free to ask. I'm here to respond.

**Comment by muhammadkarbalaee** [comment]
> please make a new branch and add the feature and when you are done, make a pull request to development branch. We'll review and merge your implementation. ich danke ihn😊

you can fork the project instead of branching as well.
