### ISSUE TITLE
Compilation issue for resolving IntWrapper after latest pull for development branch

### ISSUE THREAD

**Issue by mayur-ravindram** [muhammadkarbalaee/jalgorithm#91]
After latest pull, getting these compilation errors. Possibly due to missing dependency.

**Screenshots**
![image](https://user-images.githubusercontent.com/70086176/151664734-ae8a532b-ad80-41df-814c-813d02511e50.png)

**Comment by muhammadkarbalaee** [comment]
@cklimkowski 
Have you used any dependency? 😊

**Comment by muhammadkarbalaee** [comment]
the issue was with a missing import

**Comment by muhammadkarbalaee** [comment]
the issue was with a missing import

**Comment by muhammadkarbalaee** [comment]
and still there is a getVal method that is unknown.
can @cklimkowski  please check it out?🙏

**Comment by cklimkowski** [comment]
I have just uploaded the missing file IntWrapper.java. I should be working now. Sorry for that.
Please try it out at your earliest convenience and let me know.
